### ISSUE TITLE
Check signal mask sequence

### ISSUE THREAD

**Issue by YoannKermaidic** [dune-lardon/lardon#45]
Now, the signal mask sequence in `lardon.py` is as follow:
`- compute pedestal`
`- refine_mask`
`- compute pedestal`
`- CNR`
`- compute pedestal`
`- refine_mask`
`- compute pedestal`

However, I suggest we go back to a safer solution:
`- compute pedestal`
`- update_mask`
`- compute pedestal`
x2
`- CNR`
`- compute pedestal`
`- refine_mask`
`- compute pedestal`

**Comment by lzambell** [comment]
That's what I've implemented in my lastest PR !

**Comment by YoannKermaidic** [comment]
Indeed, thanks.
The issue can be closed.
